import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import EnhancedTable from "@/components/Paginate";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [data, setData] = useState({
    absences: null,
    members: null,
  });
  useEffect(() => {
    async function fetchData() {
      var requestOptions = {
        method: "GET",
        redirect: "follow",
      };
      const membersFetch = await fetch(`/api/members`, requestOptions);
      const absencesFetch = await fetch(`/api/absences`, requestOptions);
      const members = await membersFetch.json();
      const absences = await absencesFetch.json();
      setData({
        members: members,
        absences: absences,
      });
    }
    fetchData();
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <EnhancedTable members={data.members} absences={data.absences} />
      </main>
    </>
  );
}
